// Code generated by goctl. DO NOT EDIT.
package types

type LongToShortHandlerRequest struct {
	LongUrl  string `form:"longUrl"`
	ShortKey string `form:"shortKey,optional"`
}

type LongToShortHandlerResponse struct {
	Code     int64  `json:"Code"`
	ShortUrl string `json:"ShortUrl"`
}

type ShortToLongHandlerRequest struct {
	ShortKey string `path:"shortKey"`
}

type ShortToLongHandlerResponse struct {
	LongUrl string `json:"longUrl"`
}
