// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/xbclub/MyUrls/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:shortKey",
				Handler: ShortToLongHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/short",
				Handler: LongToShortHandler(serverCtx),
			},
		},
	)
}
